### ISSUE TITLE
Moduł algorytmów - Algorytmy Pomocniczne

### ISSUE THREAD

**Issue by Lukier1** [dawid-woj/steiner-tree#13]
- Przetwarzanie wstępne grafu
- Generowanie grafu indukowanego
- Generowanie wszystkich podzbiorów zbioru wierzchołków.

**Comment by dawid-woj** [comment]
Commit `d3c47458eaed09646b95b0db19eca9d89e812a17` dodaje klasę `Utils` w pakiecie `algorithms` ze statycznymi metoda realizującymi pomocnicze procedury/algorytmy:
- kopiowanie grafu `SingleGraph` wraz z atrybutami węzłów i krawędzi
- kopiowanie węzłów i krawędzi wraz z ich atrybutami
- generowanie wszystkich podzbiorów danego zbioru węzłów grafu
- generowanie wszystkich możliwych identyfikatorów potencjalnych krawędzi między zadanymi węzłami
- wyciąganie z `SteinerGraph` wszystkich węzłów nieterminalnych
- generowanie podgrafu indukowanego na zadanym zbiorze węzłów
- generowanie grafu z usuniętymi węzłami terminalnymi

W trakcie implementacji algorytmów KMB i Hakimi pewnie jeszcze wyjdą jakieś potrzebne metody do dodania, również **nie został zaimplementowany etap wstępnego przetwarzania grafu** (patrz: #18) - mimo to zamykam zadanie.
