### ISSUE TITLE
Kolejność sekcji w wynikowym pliku STP

### ISSUE THREAD

**Issue by dawid-woj** [dawid-woj/steiner-tree#17]
`STPSaver` generuje wyjściowe pliki STP z sekcjami w kolejności:
**Result**
Comment
Graph
Terminals
**Solution**

Z treści sprawozdania nr 2 wynika, że kolejność powinna być taka:
Comment
Graph
Terminals
**Result**
**Solution**

Trzeba te wątpliwości rozwiązać: zmodyfikować sprawozdanie i dopasować do niego kod.

**Comment by Lukier1** [comment]
Przy oddawaniu pierwszego sprawozdania była prośba żeby te statystyki dotyczące działania algorytmu znalazły się na początku pliku.

Wieć należy zmodyfikować sprawozdanie.

**Comment by dawid-woj** [comment]
Sądziłem, że prośba tyczyła się względnej kolejności sekcji **Result** i **Solution** NA KOŃCU pliku. W sprawozdaniu nr 1 propozycja była taka:
_Comment, Graph, Terminals, Solution, Result_
a w sprawozdaniu nr 2 było tak:
_Comment, Graph, Terminals, Result, Solution_

Ale chyba najbardziej sensowne wydaje mi się to, co jest teraz, więc można znowu zmodyfikować sprawozdanie.

**Comment by dawid-woj** [comment]
Zostaje tak, jak to jest teraz zaimplementowane. Zamykam.
