### ISSUE TITLE
Reprezentacja drzewa

### ISSUE THREAD

**Issue by Lukier1** [dawid-woj/steiner-tree#4]
Reprezentacja znalezionego drzewa steinara w grafie wejściowym.

**Comment by dawid-woj** [comment]
Kod z mojego commita `45a0afc5c807ac60f5e7accc24f72882eded97d6` zakłada, że **reprezentacja wynikowego drzewa Steinera jest wbudowana w reprezentację grafu wejściowego**: `SteinerGraph` - obiekt tej klasy przechowuje listę krawędzi odnalezionego drzewa; krawędzie te mają również nadany atrybut `RESULT_TREE_ATTR` w grafie.

@Lukier1 weź oceń, czy coś takiego może być. Jak tak, to można zamknąć zadanie.
