### ISSUE TITLE
Moduł kontroli

### ISSUE THREAD

**Issue by Lukier1** [dawid-woj/steiner-tree#5]
Kontrola będzie się odbywała automatycznie, będzie ona "hard kodowana" w programie. 

Założenia tego modułu:
- Służy jako "szyna" między innym modułami. Pozostałe moduły nie komunikują się w żaden sposób ze sobą.
- Komunikacja jest oparta na klasach z model.  
- Może przechowywać maksymalnie jeden graf. 
- Pomiary czasu następują w tym module. 
- Pracuje na tym samym wątku co moduł IO i moduł algorytmów, moduł wyświetlania pracuje na oddzielnym.
Całość ma być oparta na danym schemacie:
![kolejnosc obliczen](https://user-images.githubusercontent.com/5832331/34070256-24f29b78-e263-11e7-8977-d376f7c25cf6.png)

Do stworzenia:
Rozkaz ładowania pliku. 
Rozkaz wyświetlania grafu.
Rozkaz obliczania drzewa Stainera. 
Rozkaz zapisu.
Pomiar czasu.

Zależne od modeli i interfejsów dla zadań #7 , #4 , #6  a także dla interfejsu modułu algorytmicznego.

**Comment by dawid-woj** [comment]
Demko korzystania z algorytmów do wyszukiwania drzewa Steinera + generowanie wyniku pojawiło się z moim commitem `45a0afc5c807ac60f5e7accc24f72882eded97d6` w klasie `App` - można to potraktować jako **zarys** modułu kontroli w pewnym sensie.
