### ISSUE TITLE
Moduł algorytmów - Interfejs algorytmów 

### ISSUE THREAD

**Issue by Lukier1** [dawid-woj/steiner-tree#8]
Interfejs powinien pozwalać na  uruchomienie obliczeń na grafie. 
Użytkownik korzystający z interfejsu powinnen mieć możliwość wyboru używanego algorytmu. A na wyjściu powinnen zwrócić graf z drzewem Stainera, a także wyliczone parametry tego drzewa. [Może jednak pomiar czasu też tutaj????] 

Uruchamia on wstepne przetworzenie grafu. 
A także na podstawie wartości podanych dokonuje wyboru czy będzie używany algorytmy aproksymujac/NP-trudny czy można w tym przyapdku użyć Dijsktry czy Prima.

**Comment by dawid-woj** [comment]
Z commitem `45a0afc5c807ac60f5e7accc24f72882eded97d6` weszły klasy abstrakcyjne: `AbstractSpanningTreeAlgorithm` (stanowiący bazę dla klas algorytmów Dijkstry i Prima: `Dijkstra` i `Prim`) i `AbstractMinimumSteinerTreeAlgorithm` (stanowiący bazę i interfejs dla algorytmów KMB i Hakimi).
