### ISSUE TITLE
Moduł algorytmów - suma długość drzewa Stainera

### ISSUE THREAD

**Issue by Lukier1** [dawid-woj/steiner-tree#9]
Algorymy do obliczenia sumy długość drzewa Stainera,

**Comment by dawid-woj** [comment]
Jak to było wspomniane w komentarzu do zadania #4 a propos commitu `45a0afc5c807ac60f5e7accc24f72882eded97d6`: informacje o krawędziach wynikowego drzewa Steinera są dostępne w obiekcie klasy `SteinerGraph` -> metoda `getResultTreeWeight()` zwraca sumę wag tych krawędzi.

@Lukier1 weź oceń, czy coś takiego może być. Jak tak, to można zamknąć zadanie.

**Comment by Lukier1** [comment]
Jak najbardziej coś takiego odpowiada.
